spring:
  application:
    name: test_kuber
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5435/test_kuber_local
    username: test_kuber_local
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8081

jwt:
  rsa-public-key: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjZ7hnKof9GdDeW3BgCzV0C8H3wZfZtN5pviNTiAGyzcecs4f/GPYvTiATBOGaq3mbB4MzhO/qlmFJyTa1vFKlbpE8GIUg3BibkRzBgu2FNnoQIKIKZ/68LiO+KTWh5bqiy3OmdVPLoU5k1lW/sWpmMr47X8SQyllrggcmefFDVC0004SoQbqEFafAy6dx8eDn1AUjZTicljU8rzSHR/Dkpa5EfCeMnTO6xWJJ3cF5CxcqysuSwGch3Ylls7jU5o3hhjBS2VpbgyYkXDkAdGwTClwFshR/EmEXuZjhX4uE1ftxm9f14zFG2O4nG/SNZ8+ZtAn9J2M5LH2/T9BgKbEIwIDAQAB-----END PUBLIC KEY-----
  expiration: 864_000_000