apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-app.fullname" . }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "spring-app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: spring-app
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "spring-app.fullname" . }}-config
            - secretRef:
                name: {{ include "postgres.fullname" . }}-secret
            - secretRef:
                name: {{ include "spring-app.fullname" . }}-app-jwt
            # --- пробы ---
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.containerPort }}
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.containerPort }}
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.containerPort }}
              httpHeaders:
                - name: Accept
                  value: application/json
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            # Устанавливаем долгий порог, чтобы дать приложению время на запуск