{{- if .Values.kong.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-kong-ingress-public
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/auth/register
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
          - path: /api/auth/login
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
          - path: /actuator/prometheus
            pathType: Exact
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
---
{{- if .Values.kong.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-kong-ingress-protected
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/plugins: {{ include "spring-app.fullname" . }}-jwt-auth
spec:
  ingressClassName: kong
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}