{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-app.fullname" . }}-monitor
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spring-app.labels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}